### ISSUE TITLE
v0.0.5 doesn't work on Chrome v46

### ISSUE THREAD

**Issue by Deadarius** [cezary/react-webcam#15]
```navigator.mediaDevices``` is undefined, should be available in Chrome v47 though.

https://github.com/cezary/react-webcam/blob/master/src/react-webcam.js#L86

v0.0.4 works great!

**Comment by cezary** [comment]
Added a fallback for earlier versions of Chrome with the latest changes.

**Comment by Deadarius** [comment]
Thanks a lot for quick response!
