### ISSUE TITLE
Package in npm registry out-of-date?

### ISSUE THREAD

**Issue by victornguyen** [cezary/react-webcam#2]
Installing this package via `npm install react-webcam` seems to pull down an old version of the package.

Seems like it needs a version bump and an `npm publish`?

**Comment by g-p-g** [comment]
At least in terms of package.json it seems to be the latest one, but it won't cleanly install alongside react. That is `npm install react react-webcam` fails with

```
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-webcam@0.0.1 wants react@^0.12.1
```

It seems like there should be a new release anyway.

**Comment by cezary** [comment]
Should work now.
