### ISSUE TITLE
this.stream.stop is not a function

### ISSUE THREAD

**Issue by IgorKirey** [cezary/react-webcam#20]
In latest Chrome I've got this error "this.stream.stop is not a function" when I'm trieng to make capture with "getScreenshot" function.

**Comment by IgorKirey** [comment]
Seems it's not "getScreenshot" function issue.

**Comment by IgorKirey** [comment]
Anybody here?

**Comment by Moussawi7** [comment]
+1 Same issue.

**Comment by yemel** [comment]
Same here

**Comment by cezary** [comment]
The pr from @rexxars should fix this.

**Comment by nisarg-parikh** [comment]
You can enable-disable the stream.
like this way :
 var _streams = this.refs.webcam.stream;
                _streams.getTracks().filter(function (stream) {
                    stream.enabled = false
                })
