### ISSUE TITLE
React v0.14 support

### ISSUE THREAD

**Issue by steveherschleb** [cezary/react-webcam#22]
With React v0.14, there's now this console message: 

> Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

Not a big deal, but I just wanted to document it.

**Comment by jessepollak** [comment]
:+1: 

thanks for a great component!

**Comment by cezary** [comment]
Sorry for the delay, I updated the version and added react-dom.

**Comment by jessepollak** [comment]
Woot — thanks!
